services:
- type: web
  name: strapi
  env: node
  plan: free
  repo: https://github.com/bagasranggen/strapi-cms-films
  branch: master
  buildCommand: yarn install && yarn build
  startCommand: yarn start
  healthCheckPath: /_health
  autoDeploy: false
  envVars:
    - key: NODE_VERSION
      value: ~16.13.0
    - key: NODE_ENV
      value: production
    - key: DATABASE_FILENAME
      value: /data/strapi.db
    - key: JWT_SECRET
      generateValue: true
    - key: API_TOKEN_SALT
      generateValue: true
    - key: ADMIN_JWT_SECRET
      generateValue: true
    - key: APP_KEYS
      generateValue: true
    - key: DATABASE_URL
      fromDatabase:
        name: strapi
        property: connectionString

databases:
  - name: strapi
    plan: free # This database will expire 90 days after creation
